server:
  port: 8085
  servlet:
    context-path: /

# db config
spring:
  profiles:
    active: jdbc
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://35.72.73.240:3306/attence?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true
    username: root
    password: Syougeisyainfo1
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false
  devtools:
    restart:
      #      是否启用重启
      enabled: true
      #      设置重启的目录
      additional-paths: src/main/java
      #classpath目录下的WEB-INF文件夹内容修改不重启
      spring.devtools.restart.exclude: WEB-INF/**
  messages:
    basename: messages/message_ja_Jp
  mail:
    host: smtp.gmail.com
    username: office@shangyistudiotokyo.com
    password: 3314yushima
    protocol: smtp
    properties.mail.smtp.auth: true
    properties.mail.smtp.port: 465
    properties.mail.display.sendmail: office@shangyistudiotokyo.com
    properties.mail.display.sendname: office@shangyistudiotokyo.com
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    from: office@shangyistudiotokyo.com
    default-encoding: utf-8
# thymeleaf
thymeleaf:
 prefix: classpath:/templates/
 check-template-location: true
 suffix: .html
 encoding: UTF-8
 servlet.content-type: text/html
 mode: HTML5
 cache: false

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.my.attence.entity
  global-config:
    # 逻辑删除配置
    db-config:
      # 删除前
      logic-not-delete-value: 1
      # 删除后
      logic-delete-value: 0
      logic-delete-field: deleted
  logging:
    level:
      root: info
      com.example: debug



